FROM node:16
WORKDIR /app

# Copy package files
COPY frontend/ghi/package.json frontend/ghi/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY frontend/ghi /app/

CMD ["npm", "run", "dev"]
