FROM python:3.9-slim
WORKDIR /app
# Copy the Python dependencies and install them
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
# Copy the Django project into the container
COPY . /app/
